export const productData = [
  {
    id: 1,
    Img: "https://secondbucketforcustompc.s3.us-east-2.amazonaws.com/TestPC1.jpg",
    Des: "TEST DATA",
    Des2: "Designed for light application usage, Curated for maximum performance and economic modality",
    Img2: "https://secondbucketforcustompc.s3.us-east-2.amazonaws.com/SSD.jpg",
    Des3: "Colossal Storage",
    Des4: "enjoy seamless transitions between application, effortless browsing and increased productivity with our latest ssd",
    Img3: "https://secondbucketforcustompc.s3.us-east-2.amazonaws.com/i57500.jpg",
    Des5: "NPX computers features the robust Processors from Intel, the i5-7500",
    Img4: "https://secondbucketforcustompc.s3.us-east-2.amazonaws.com/GTX1060.jpg",
    Des6: "Enjoy mega smooth, stutter free, tear free gaming with NVIDIA GTX 1060",
    Img5: "https://secondbucketforcustompc.s3.us-east-2.amazonaws.com/Ram2.1.jpg",
    Des7: "16GB RAM DDR4 Vengeance, enjoy strong performance while running multiple tasks",

    type: "Home Office",
    tab: 3,
    app: 1,
    budget: 500,
  },
  {
    id: 2,
    Img: "https://secondbucketforcustompc.s3.us-east-2.amazonaws.com/playstation.jpg",
    Description: "Product: Home Office,  tab 3, app 1, bud 1200",
    type: "Home Office",
    tab: 2,
    app: 2,
    budget: 1200,
  },
  {
    id: 3,
    Img: "https://secondbucketforcustompc.s3.us-east-2.amazonaws.com/playstation.jpg",
    Description: "Product: Home Office, tab 1, app 3, bud 3000",
    type: "Home Office",
    tab: 1,
    app: 3,
    budget: 3000,
  },
  {
    id: 4,
    Img: "https://secondbucketforcustompc.s3.us-east-2.amazonaws.com/playstation.jpg",
    Description: "Test Description 2",
    type: "Content Creation",
  },
  {
    id: 5,
    Img: "https://secondbucketforcustompc.s3.us-east-2.amazonaws.com/playstation.jpg",
    Description: "Test Description 3",
    type: "Gaming",
  },
];
