export const COMPUTER_LEAD_REQUEST = 'COMPUTER_LEAD_REQUEST'
export const COMPUTER_LEAD_SUCCESS = 'COMPUTER_LEAD_SUCCESS'
export const COMPUTER_LEAD_FAIL = 'COMPUTER_LEAD_FAIL'
export const COMPUTER_LEAD_RESET = 'COMPUTER_LEAD_RESET'