export const PAYMENT_REQUEST = "PAYMENT_REQUEST";
export const PAYMENT_SUCCESS = "PAYMENT_SUCCESS";
export const PAYMENT_FAIL = "PAYMENT_FAIL";
export const MAKE_PAYMENT_METHOD_REQUEST = "MAKE_PAYMENT_METHOD_REQUEST";
export const MAKE_PAYMENT_METHOD_SUCCESS = "MAKE_PAYMENT_METHOD_SUCCESS";
export const MAKE_PAYMENT_METHOD_FAIL = "MAKE_PAYMENT_METHOD_FAIL";
