export const STEPONE_CONVERT = "STEPONE_CONVERT";
export const STEPTWO_CONVERT = "STEPTWO_CONVERT";
export const STEPTHREE_CONVERT = "STEPTHREE_CONVERT";
export const STEPFOUR_CONVERT = "STEPFOUR_CONVERT";
export const STEPFIVE_CONVERT = "STEPFIVE_CONVERT";
