export const VALIDATION_REQUEST = "VALIDATION_REQUEST";
export const VALIDATION_SUCCESS = "VALIDATION_SUCCESS";
export const VALIDATION_FAIL = "VALIDATION_FAIL";
export const VALIDATION_RESET = "VALIDATION_RESET";
