import Head from 'next/head'
import Image from 'next/image'

import { Row, Col, Button } from 'react-bootstrap'
import axios from 'axios'
import { API_URL } from '../config/index'

export default function HomeScreen() {
  
  const Testclick = async() => {
    try {
      const { data } = await axios.get(`${API_URL}/api/lead`)
      console.log( data )
    } catch (error) {
      console.log(error.response)
    }
    
  }
  
  return (
    <>
      <Row>
        <Col>
          <Image
            src={
              'https://secondbucketforcustompc.s3.us-east-2.amazonaws.com/playstation.jpg'
            }
            width={170}
            height={100}
          />
        </Col>
        <Col>
          <Image
            src={
              'https://secondbucketforcustompc.s3.us-east-2.amazonaws.com/playstation.jpg'
            }
            width={170}
            height={100}
          />
        </Col>
        <Col>
          <Image
            src={
              'https://secondbucketforcustompc.s3.us-east-2.amazonaws.com/playstation.jpg'
            }
            width={170}
            height={100}
          />
        </Col>
        h
        <Button
          type='button'
          className='btn-block' 
          onClick={() => Testclick()}>
            Test Button
        </Button>

      </Row>
    </>
  )
}

//eliminate need for axios request on first render, get product images from s3

// export default function Home() {
//   return (
//     <div className={styles.container}>
//       <Head>
//         <title>Create Next App</title>
//         <meta name="description" content="Generated by create next app" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>

//       <main className={styles.main}>
//         <h1 className={styles.title}>
//           Welcome to <a href="https://nextjs.org">Next.js!</a>
//         </h1>

//         <p className={styles.description}>
//           Get started by editing{' '}
//           <code className={styles.code}>pages/HELLO.js</code>
//         </p>

//         <div className={styles.grid}>
//           <a href="https://nextjs.org/docs" className={styles.card}>
//             <h2>Documentation &rarr;</h2>
//             <p>Find in-depth information about Next.js features and API.</p>
//           </a>

//           <a href="https://nextjs.org/learn" className={styles.card}>
//             <h2>Learn &rarr;</h2>
//             <p>Learn about Next.js in an interactive course with quizzes!</p>
//           </a>

//           <a
//             href="https://github.com/vercel/next.js/tree/master/examples"
//             className={styles.card}
//           >
//             <h2>Examples &rarr;</h2>
//             <p>Discover and deploy boilerplate example Next.js projects.</p>
//           </a>

//           <a
//             href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//             className={styles.card}
//           >
//             <h2>Deploy &rarr;</h2>
//             <p>
//               Instantly deploy your Next.js site to a public URL with Vercel.
//             </p>
//           </a>
//         </div>
//       </main>

//       <footer className={styles.footer}>
//         <a
//           href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//           target="_blank"
//           rel="noopener noreferrer"
//         >
//           Powered by{' '}
//           <span className={styles.logo}>
//             <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
//           </span>
//         </a>
//       </footer>
//     </div>
//   )
// }
